version: '3'
services:
  # api:
  # worker:
  redis:
    image: redis:7.4
    restart: always
    ports:
      - '6379:6379'
    # command: redis-server --save 60 1 --loglevel warning --requirepass <PASSWORD>
    # volumes: 
    #   - ./data:/data
