apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
  - name: redis-datasource-profilingdata
    type: redis-datasource
    access: proxy
    url: redis://host.docker.internal:6379/3
    isDefault: false
    editable: true